name: "Selim Öber"
description: "Selim Öber - Home page, blog, timeline and other uninsteresting stuff."

url: "http://localhost:4000"
#url: "selimober.com"

markdown: rdiscount
permalink: pretty
highlighter: pygments